indentation: 2
excluded:
  - bazel-bin
  - bazel-out
  - bazel-testlogs
  - bazel-xcodeproj-bazel
  - build-input
  - build-system
  - HelloWorld/iOS/Application.swift
  - HelloWorld/iOS/main.m
disabled_rules:
  - nesting
opt_in_rules:
  - prohibited_interface_builder
  - convenience_type
  - sorted_imports
  - unused_import
  - yoda_condition
  - vertical_parameter_alignment_on_call
force_cast: warning
force_try: warning
legacy_hashing: error
indentation_width:
  indentation_width: 2
trailing_comma:
  mandatory_comma: true
identifier_name:
  max_length: 
    warning: 60 
    error: 80